# Generated by Django 2.2.8 on 2021-04-09 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('limit', models.IntegerField()),
                ('status', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('sign', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('create_time', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sign.Event')),
            ],
            options={
                'unique_together': {('event', 'phone')},
            },
        ),
    ]
